# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - sudo docker run --rm -v ${PWD}:/local docker.1ms.run/openapitools/openapi-generator-cli generate -i /local/openapi.json -g go -o /local